language: rust
rust:
  - stable
env:
  global:
    - RUST_BACKTRACE=1
install:
  - test [ $(rustfmt -V) == *"0.9.0"* ] || cargo install -f --vers 0.9.0 rustfmt
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --write-mode=diff
  - git diff-files --quiet
cache: cargo
